### ISSUE TITLE
Documentation doesn't cover passing `components: {}` to the component

### ISSUE THREAD

**Issue by nikitindiz** [nuxt-community/nuxt-property-decorator#11]
Documentation doesn't cover passing `components: {}` to the component. It there a way to do that?

**Comment by Try-Parser** [comment]
@nikitindiz  is this what you meant ? 

```
@Component({
  components: { comp }
})
export default class Sample extends Vue {}
```

**Comment by Try-Parser** [comment]
@stevefan1999  then i think you have and error import occur before the 

> @Component

 can i see your code?

**Comment by DavidBernal** [comment]
Added @Try-Parser example to readme.
