### ISSUE TITLE
Issue with layout & auth property

### ISSUE THREAD

**Issue by naveensky** [nuxt-community/nuxt-property-decorator#14]
I am trying to use `nuxt-property-decorator` but I am finding it not working with `layout` & `auth` properties for nuxt.js and auth.nuxt.js.

I am trying to set `layout = 'empty'` and expect the component to use empty layout. It instead picks the default layout. Same is the issue with `auth = false` when using nuxt's auth module. The component should ideally be skipped from auth routes but it doesn't work that way. 

I would like to understand if I am missing any class/property attribute to use to configure the component as required. 

More information for auth at https://auth.nuxtjs.org/middleware.html and custom layout is available at https://nuxtjs.org/guide/views#layouts

**Comment by Try-Parser** [comment]
on layout you must declare it as a function or methods like 

`layout () { 
  return "layout name" 
}`

**Comment by husayt** [comment]
Seems this can be closed now.

**Comment by oppianmatt** [comment]
is this fixed because that doesn't work at all

![image](https://user-images.githubusercontent.com/48596/55901947-576c2900-5bc2-11e9-9c84-ee4f065ffcc1.png)


https://codesandbox.io/s/py6rwml0jq?fontsize=14&module=%2Fpages%2Ftwo.vue

**Comment by IlyaSemenov** [comment]
FWIW, I'm augmenting the component options with:

```ts
// Nuxt.js component options
declare module 'vue/types/options' {
	interface ComponentOptions<V extends Vue> {
		layout?: string
	}
}
```

and then:

```vue
<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'

@Component({
	layout: 'simple',
})
export default class UserPage extends Vue {
```

Same for other Nuxt component options like `fetch`.
