### ISSUE TITLE
Integration with vue-apollo

### ISSUE THREAD

**Issue by stevefan1999** [nuxt-community/nuxt-property-decorator#16]
Right now, the smart query/subscrition of `vue-apollo` must be put into the class decorator of `Component`, and there're a lot of typing Catch-22s we had to turn off type checking temporarily to get it to stop redding our IDE. Is there any decorators for vue-apollo? It would be much better.

**Comment by stevefan1999** [comment]
Hang on, wrong repo😑.

**Comment by bieleckim** [comment]
@stevefan1999-personal Do You found answer for this question? We have similar problem in our project, can u please look here - https://stackoverflow.com/questions/53173685/apollo-is-not-assignable-to-parameter-of-type-vueclassvue - thanks :)

**Comment by stevefan1999-personal** [comment]
@bieleckim The only workaround is to cast it into any...
