### ISSUE TITLE
transition property not supported?

### ISSUE THREAD

**Issue by tunarob** [nuxt-community/nuxt-property-decorator#19]
How can I define a `transition` property with this lib (https://nuxtjs.org/api/pages-transition/)?

Looks like defining it as a method doesn't work:

```
import { Component, Vue } from 'nuxt-property-decorator'
@Component
export default class extends Vue {
  transition (to, from) {
    // something here
  }
}
```

Also can't see it's possible to define it within a component?

**Comment by husayt** [comment]
@tunarob see [here](https://codesandbox.io/s/1q478mzyvj) for working example

**Comment by moltar** [comment]
I'm also having problems getting transitions to work.

Example seems to be using the `transition` tag explicitly, and not actually using page transitions.
