### ISSUE TITLE
inject enhance? 

### ISSUE THREAD

**Issue by xiaoxiaocoder** [nuxt-community/nuxt-property-decorator#21]
If I want inject default value like this:
`
const Child = {  inject: {    foo: {      from: 'bar',      default: 'foo'    }  }}
`
How should I write it?  thx ;)

**Comment by DavidBernal** [comment]
Currently you can't. If you want do a PR, inject method is here: [https://github.com/nuxt-community/nuxt-property-decorator/blob/14129cb3f29ca33096d3eb29de2f3b1061194907/src/nuxt-property-decorator.ts#L33](Github)

**Comment by husayt** [comment]
We are now using inject from vue-property-decorator and that supports default values.
```
@Inject(options?: { from?: InjectKey, default?: any } | InjectKey) decorator
```
See [here](https://github.com/kaorun343/vue-property-decorator)
