### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by husayt** [nuxt-community/nuxt-property-decorator#22]
@breakingrobot @DavidBernal first of all thanks for this library which is adding lots of value. I can see there are number of issues and merge requests have not been dealt with for last 8 months. I would be happy to offer to go through merge requests and help in maintaining the library.

**Comment by DavidBernal** [comment]
You are welcome. Thank you.

**Comment by DavidBernal** [comment]
I can't add collaborators. Maybe @Atinux can.

**Comment by husayt** [comment]
Thanks, @DavidBernal.

@Atinux, @pi0 , please?

**Comment by pi0** [comment]
@husayt perm granted. Assuming @DavidBernal  already approved this :)

**Comment by husayt** [comment]
Thanks @DavidBernal and  @pi0 ,

I also plan to add number of TS relates demos and help to maintain this  very useful library

Pooya, please, can you also add me to nuxt-community as well?

**Comment by pi0** [comment]
Sure. Welcome ❤️

**Comment by pi0** [comment]
@husayt Only please first make repository maintainers (original author) aware if you plan to work on community projects.

**Comment by husayt** [comment]
Of course. I just don't want to disturb you each time

**Comment by DavidBernal** [comment]
Welcome @husayt and thank you @pi0
