### ISSUE TITLE
Importing from vue-property-decorator

### ISSUE THREAD

**Issue by husayt** [nuxt-community/nuxt-property-decorator#27]
There is some overlap with [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator) which is also using vue-class-component.

I suggest we import those overlapping methods from `vue-property-decorator`, since that library is well tested and is widely used.

`Inject, Provide, Model, Prop, Watch, Emit` should work for Nuxt the same way as they work for Vue. Also seems their implementation, although is pretty much the same, resolves some of the existing issues here like #21. 

What do you think guys? 

//cc @DavidBernal @breakingrobot and others

**Comment by qm3ster** [comment]
Pretty sure that's where they came from initially, so they must have fixed that since.

**Comment by husayt** [comment]
This is done now. Will be great to get your feedback before release. There is only one breaking change and that is renaming `mixins` to `Mixins ` to keep inline with vue-property-decorator
