### ISSUE TITLE
`watchQuery` can't work with `v2.1.3`

### ISSUE THREAD

**Issue by shalldie** [nuxt-community/nuxt-property-decorator#34]
`watchQuery` can't work with `v2.1.3`

I tried it like this:

```ts
import { Vue, Component } from 'nuxt-property-decorator';


@Component({
     ...
})
export default class IndexPage extends Vue {

    watchQuery: string[] = ['label', 'page'];
...
```

So strange, i see other hooks like `asyncData` works well, but `watchQuery` does nothing when query changes.

Here is a repository to show a demo: https://github.com/shalldie/nuxt-ts-watchQuery

**Comment by husayt** [comment]
Thanks for reporting. Let me investigate to see what's going on there.

**Comment by hartmut-co-uk** [comment]
Hi @shalldie it's part of `ComponentOptions`...
try following:

```ts
@Component({
  ...,
  watchQuery: ['label', 'page']
})
export default class IndexPage extends Vue {    
...
```

**Comment by shalldie** [comment]
@hartmut-co-uk 

yes it works for me. Thank u.

But it seems that i should to write the `.d.ts` extend for type `ComponentOptions` by myself?

This lib says it add hooks for class, so i think `watchQuery` could be a field/method of class ,which likes `asyncData`.

**Comment by hartmut-co-uk** [comment]
Apologies, I didn't notice there's been new releases since yesterday - I'll have another look tomorrow.

**Comment by shalldie** [comment]
I found that,

`watchQuery` must be part of `ComponentOptions`
`layout` must be a `static field of class`.

I think thease should be the `fields of class instance`, or, a description should be in the `readme.md`

**Comment by husayt** [comment]
@shalldie have this been resolved or you still have the problem?

**Comment by shalldie** [comment]
@husayt  it works with what @hartmut-co-uk said, let me close this issue.

**Comment by genu** [comment]
Can we have some clarity here? I don't think I understand the accepted workaround.

I get typing error when I add `watchQuery` to `@Component`

![image](https://user-images.githubusercontent.com/928780/71647381-11ad3e80-2cc4-11ea-9283-dbf002529c87.png)
