### ISSUE TITLE
Prop Use Error

### ISSUE THREAD

**Issue by xyjwsj** [nuxt-community/nuxt-property-decorator#35]
Compile error with @prop project, error message ( Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode. To use proposal-class-properties in spec mode with decorators, wait for the next major version of decorators in stage 2. )

This is my code:

export default class Wrap extends Vue {
    @Prop() nextBtn
}
use: <Wrap @nextpage="toNextPage" :nextBtn="next">

**Comment by husayt** [comment]
In latest nuxt it should have worked out of the box because it is adding
this babel plugins, but for some reason they are ignored in generate mode.

Just add this to your nuxt-config for now and hopefully nuxt issue will
make this redundant soon.

build: {
    babel: {
      plugins: [
        [
          "@babel/plugin-proposal-decorators",
          {
            legacy: true
          }
        ],
        [
          "@babel/plugin-proposal-class-properties",
          {
            loose: true
          }
        ]
      ],
