### ISSUE TITLE
layout does not work

### ISSUE THREAD

**Issue by oppianmatt** [nuxt-community/nuxt-property-decorator#40]
https://codesandbox.io/s/py6rwml0jq?fontsize=14&module=%2Fpages%2Ftwo.vue

specifying the layout as a string, method, etc all doesn't work and always uses the default layout, only object based specification works

there is this issue that was closed https://github.com/nuxt-community/nuxt-property-decorator/issues/14

**Comment by amritk** [comment]
I am experiencing this bug as well

**Comment by skyrpex** [comment]
Looks like it's working on the provided link. It also works in my project.

**Comment by amritk** [comment]
Yea it works in the link, but it seems to only be broken when trying to set the layout of an error page using the class structure.

**Comment by amritk** [comment]
Try this https://codesandbox.io/embed/7zl9q0w470 and trigger the error page by hitting a route which doesn't exist

**Comment by husayt** [comment]
It works for me. Am I missing something?

**Comment by amritk** [comment]
@husayt did you try my codesandbox? https://codesandbox.io/embed/7zl9q0w470

**Comment by husayt** [comment]
Yes, but I couldn't notice any problem with that.

**Comment by amritk** [comment]
Type in a route which does not exist to see the error page, you will see that it uses the default layout, instead of the "second" layout which is specified in the error component.

**Comment by husayt** [comment]
Try latest nuxt. This seems like  the same issue 
https://github.com/nuxt/nuxt.js/pull/6479
