### ISSUE TITLE
`mixins` and `Mixins`

### ISSUE THREAD

**Issue by antfu** [nuxt-community/nuxt-property-decorator#41]
Just get interested in this library. Love the all-in-one solution!

I am currently using `vue-property-decorator` and `vuex-class`, trying to migrate to this package. 

Just wondering, what's the differences between `Mixins` from `vue-property-decorator` and `mixins` from `vue-class-component` ? Why you choose `mixins` over `Mixins`? (`Mixins` works perfectly in my case.)

Or can we export both for easier migration?

**Comment by husayt** [comment]
mixins vs Mixins is I guess a matter of taste. In our case we wanted to keep more in line with `vue-class-component` as it is a key dependency enabling most of the features of this library and make it easy for people upgrading from it to `nuxt-property-decorator`
