### ISSUE TITLE
No 'Ref' decorator

### ISSUE THREAD

**Issue by profispojka** [nuxt-community/nuxt-property-decorator#49]
This module does not support Ref decorator, although vue-property-decorator does support it

**Comment by kevinmarrec** [comment]
@profispojka I think it's cause it's a feature that has been implemented in `vue-property-decorator` 8.2.x but `nuxt-property-decorator` uses 8.1.

Can you try using last version of `vue-property-decorator` by forcing it to insall last version in your project ?

**Comment by profispojka** [comment]
This won't work, as the functions are hardcoded in nuxt-property-decorator.umd.js and types in nuxt-property-decorator.d.ts

**Comment by kevinmarrec** [comment]
Indeed you're right, we need to upgrade dependencies and release new version.
/cc @husayt

**Comment by husayt** [comment]
This is on the way. Thanks for pointing out.

**Comment by profispojka** [comment]
Hi. Do you have estimate when this is going to be finished?

**Comment by husayt** [comment]
@profispojka  new 2.4.0 with latest vue-property-decorator has been released today. Can you please give it a try and also would be great to have an example of using `ref` decorator

**Comment by profispojka** [comment]
I don't see that you have added the export of Ref decorator. Only a note in release notes.
