### ISSUE TITLE
Parsing error: Unexpected token

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/nuxt-property-decorator#50]
```
@Component
class Def extends Vue {
  public language: string = 'en'
}
```

causes an error during compilation: `error  Parsing error: Unexpected token`

We cannot use `public`, `private` with nuxt property decorator?

**Comment by MarvinRudolph** [comment]
I get the same error pointing to the "!" with:
```ts
@Prop() test!: string
```

What could be wrong?

**Comment by husayt** [comment]
Works for me with Typescript. Are you using JS or TS? If using JS need to add access modifier support in your nuxt project.

**Comment by husayt** [comment]
@webcoderkz thanks for bring this to our attention. This has been now resolved in latest release
