### ISSUE TITLE
Reflect-metadata is not working

### ISSUE THREAD

**Issue by victorgarciaesgi** [nuxt-community/nuxt-property-decorator#55]
I'm importing reflect-metadata on a plugin because i don't know where to put it, but it doesn't work.
Where do you import it?

**Comment by lifenautjoe** [comment]
Same quetion here!

**Comment by victorgarciaesgi** [comment]
@Atinux Any news? :(

**Comment by husayt** [comment]
Sorry for delay. I am packaging a new version with fixes for today .

**Comment by victorgarciaesgi** [comment]
@husayt  Thanks! 👍

**Comment by husayt** [comment]
New version is out. Do you still have a problem?

**Comment by husayt** [comment]
I don't understand why are you importing reflect-metadata and what is the problem. What do you mean by "reflect-metadata is not working"?

I use this library both in JS and TS without any issues

**Comment by lifenautjoe** [comment]
Reflect metadata in my case is needed for tsyringe, a dependency injection
container which uses reflection data to resolve items.

It works when running the plugin without SSR. When adding

‘’’
import “reflect-metadata”
‘’’

In a plug-in with SSR, the application fails with an error suggesting to
import reflect metadata as the metadata attributes were not found.

Once again, everything works fine without SSR.

**Comment by husayt** [comment]
It seems like this is an issue in nuxt itself. In any case this is not an issue with `nuxt-property-decorator`, so  hence closing,

**Comment by youncccat** [comment]
@victorgarciaesgi same problem, do you resolve it? :(

**Comment by lifenautjoe** [comment]
Nope, we had to disable SSR :-( @altinux

**Comment by youncccat** [comment]
@lifenautjoe I think I solved it :)

```javascript
if (process.client) {
  middlewareProcessor($axios)
}
```
`middlewareProcessor` include `logger.js` that import `reflect-metadata`, but the file throw a error `defineMetadata is not a function` when I restart.

this is my `logger.js`
```javascript
import { RequestInterceptor, All } from '../decorators'

@RequestInterceptor
export class Logger {
  @All('/')
  logReqDetail(config) {
        console.log(config)
    return config
  }
}
```

I think It throws an error because decorator is created when `logger.js` is imported which means it is added to the dependency graph that JS engine can exec.

So, It's must be imported lazy, I added the following code fragment to `middlewareProcessor`
```javascript
const logger = await import("./logger.js")
```
It will be working because logger.js is always running on browser~

Hope this helps.

**Comment by adinvadim** [comment]
Add middleware middleware/_reflect.ts 

"_" in filename is required, that this middleware require first.

```
import 'reflect-metadata';

export default () => {
  throw new Error('Its hack for correct working reflect metadata on server');
};
```

Because `import middleware from './middleware.js'` it's first user code that include in .nuxt/server.js

**Comment by JCtapuk** [comment]
> 

[nitro] [uncaughtException] TypeError: Reflect.getMetadata is not a function                                                               5:35:41 AM
    at /workspaces/magicland-game/node_modules/class-transformer/cjs/decorators/type.decorator.js:13:39
    at __decorateClass (file:///workspaces/magicland-game/.nuxt/dev/index.mjs:871:24)
    at file:///workspaces/magicland-game/.nuxt/dev/index.mjs:905:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

**Comment by JCtapuk** [comment]
> Добавление промежуточного ПО промежуточного слоя/_reflect.ts
> 
> "_" в имени файла является обязательным, что это промежуточное программное обеспечение требует в первую очередь.
> 
> ```
> import 'reflect-metadata';
> 
> export default () => {
>   throw new Error('This is hack for correct working reflect metadata on server');
> };
> ```
> 
> Потому что это первый пользовательский код, который включается в .nuxt/server.js`import middleware from './middleware.js'`

fromNodeMiddleware

**Comment by JCtapuk** [comment]
> Добавление промежуточного ПО промежуточного слоя/_reflect.ts
> 
> "_" в имени файла является обязательным, что это промежуточное программное обеспечение требует в первую очередь.
> 
> ```
> import 'reflect-metadata';
> 
> export default () => {
>   throw new Error('This is hack for correct working reflect metadata on server');
> };
> ```
> 
> Потому что это первый пользовательский код, который включается в .nuxt/server.js`import middleware from './middleware.js'`

Nuxi 3.6.1                                                                                                                                                  5:42:25 AM
Nuxt 3.6.1 with Nitro 2.5.2                                                                                                                                 5:42:25 AM
                                                                                                                                                            5:42:26 AM
  > Local:    http://localhost:3000/ 
  > Network:  http://172.16.5.4:3000/
                                                                                                                                                            5:42:24 AM
✔ Nuxt Devtools is enabled v0.6.6 (experimental)                                                                                                           5:42:26 AM
ℹ Vite client warmed up in 2349ms                                                                                                                          5:42:29 AM
✔ Nitro built in 1061 ms                                                                                                                             nitro 5:42:30 AM
[nitro] [uncaughtException] TypeError: Reflect.getMetadata is not a function                                                                                5:42:31 AM
    at /workspaces/magicland-game/node_modules/class-transformer/cjs/decorators/type.decorator.js:13:39
    at __decorateClass (file:///workspaces/magicland-game/.nuxt/dev/index.mjs:871:24)
    at file:///workspaces/magicland-game/.nuxt/dev/index.mjs:905:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

**Comment by JCtapuk** [comment]
> Add middleware middleware/_reflect.ts
> 
> "_" in filename is required, that this middleware require first.
> 
> ```
> import 'reflect-metadata';
> 
> export default () => {
>   throw new Error('This is hack for correct working reflect metadata on server');
> };
> ```
> 
> Because `import middleware from './middleware.js'` it's first user code that include in .nuxt/server.js

Nuxi 3.6.1                                                                                                                                                  5:42:25 AM
Nuxt 3.6.1 with Nitro 2.5.2                                                                                                                                 5:42:25 AM
                                                                                                                                                            5:42:26 AM
  > Local:    http://localhost:3000/ 
  > Network:  http://172.16.5.4:3000/
                                                                                                                                                            5:42:24 AM
✔ Nuxt Devtools is enabled v0.6.6 (experimental)                                                                                                           5:42:26 AM
ℹ Vite client warmed up in 2349ms                                                                                                                          5:42:29 AM
✔ Nitro built in 1061 ms                                                                                                                             nitro 5:42:30 AM
[nitro] [uncaughtException] TypeError: Reflect.getMetadata is not a function                                                                                5:42:31 AM
    at /workspaces/magicland-game/node_modules/class-transformer/cjs/decorators/type.decorator.js:13:39
    at __decorateClass (file:///workspaces/magicland-game/.nuxt/dev/index.mjs:871:24)
    at file:///workspaces/magicland-game/.nuxt/dev/index.mjs:905:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

**Comment by bre30kra69cs** [comment]
I have this issue because I import in Nuxt config util that reexported with decorated class. For me this error was actual because app specific code was imported to nuxt.config.ts file
