### ISSUE TITLE
`meta` property is not present in componentOptions

### ISSUE THREAD

**Issue by MohitTilwani15** [nuxt-community/nuxt-property-decorator#57]
Meta property needs to be added in the component options

https://github.com/nuxt-community/nuxt-property-decorator/blob/930298ab951e86861c1cc5b471dce6df424434dc/src/nuxt-property-decorator.ts#L16

As you can see in the below link, the meta property is being added in nuxt typescript build

https://github.com/nuxt/typescript/blob/9fa04b66f00c875cb1b690462a52e10056926759/packages/types/app/vue.d.ts#L23

**Comment by husayt** [comment]
This has been resolved in latest release.
