### ISSUE TITLE
No overload matches this call. When using middleware

### ISSUE THREAD

**Issue by mewis** [nuxt-community/nuxt-property-decorator#58]
I have the following component...

```
<template>
  <div>
    home
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'

@Component({
  middleware: ['auth']
})
export default class HomePage extends Vue {}
</script>

<style lang="scss" scoped></style>
```

the middleware hook is doing as expected but my ide throws the error...

> No overload matches this call.
  Overload 1 of 2, '(options: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> & ThisType<Vue>): <VC extends VueClass<...>>(target: VC) => VC', gave the following error.
    Argument of type '{ middleware: string[]; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> & ThisType<Vue>'.
      Object literal may only specify known properties, and 'middleware' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> & ThisType<Vue>'.
  Overload 2 of 2, '(target: VueClass<Vue>): VueClass<Vue>', gave the following error.
    Argument of type '{ middleware: string[]; }' is not assignable to parameter of type 'VueClass<Vue>'.
      Object literal may only specify known properties, and 'middleware' does not exist in type 'VueClass<Vue>'.

I cant see anywhere in the docs that covers adding specific types for the decorator.

Is there a extra step in setting this up that I am missing?

**Comment by husayt** [comment]
I just released v 2.7.1 of the library which fixes many issues. I will close thise issue, if this is still an issue please let me know
