### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by pairmix** [nuxt-community/nuxt-property-decorator#66]
Hi, i get this error:

![image](https://user-images.githubusercontent.com/33130887/75204140-5effd680-5770-11ea-94bd-5a4dd28b18cf.png)

**Comment by phamducquanptit** [comment]
i same problem. it simple remove: 
parserOptions: {
  parser: 'babel-eslint'
}
in .eslintrc.js

**Comment by husayt** [comment]
I just released v 2.7.1 of the library which fixes many issues. If your issues still exists please, provide a link to codesandbox with the issue

**Comment by glemmatim** [comment]
I had the same issue but it's fixed by using `parser: '@typescript-eslint/parser'`, instead of using `parser: 'babel-eslint'`. Apperently babel-eslint doesn't support typescript decorators: https://github.com/symfony/webpack-encore/issues/659#issuecomment-544384642
