### ISSUE TITLE
New fetch and fetchOnServer - Nuxt 2.12.x 

### ISSUE THREAD

**Issue by Jamiewarb** [nuxt-community/nuxt-property-decorator#72]
Nuxt 2.12+ has changed the way `fetch` works. As the name is the same, this is thankfully supported by nuxt-property-decorator.

However, it also introduces a new hook called `fetchOnServer` which is a variable, taking a true or false value. Docs for it can be found here: https://nuxtjs.org/api/pages-fetch/.

I can't seem to get this to work using nuxt-property-decorator. I am wondering if it needs to be registered as a hook, the same way `head` is for example.

As a temporary fix, I can write it in the registerHooks, which seems to then work, however I then must write the hook as a function, rather than a boolean:

```js
Component.registerHooks(['fetchOnServer']);

@Component
export default class MyComponent extends Vue {
  fetchOnServer() { return false };
}
```

**Comment by Jamiewarb** [comment]
Hey @husayt! Any word on this?

**Comment by VitorMarques** [comment]
`@Component({
  fetchOnServer: false
})`

**Comment by VitorMarques** [comment]
`@Component({ fetchOnServer: false })`
