### ISSUE TITLE
Subsequent property declarations must have the same type.  Property '$store' must be of type 'Store<any>', but here has type 'Store<any>'

### ISSUE THREAD

**Issue by matteotrapani** [nuxt-community/nuxt-property-decorator#74]
Hi there,

I have the following error when building my application(_nuxtJS in typescript_) with the latest version of this package(**2.7.2**)

> ERROR in D:/development/coronaresponse/node_modules/nuxt-property-decorator/node_modules/vuex/types/vue.d.ts(16,5):
16:5 Subsequent property declarations must have the same type.  Property '$store' must be of type 'Store<any>', but here has type 'Store<any>'.
    14 | declare module "vue/types/vue" {
    15 |   interface Vue {
  > 16 |     $store: Store<any>;
       |     ^
    17 |   }
    18 | }
    19 | 

This is a fatal error which breaks production build.
I have the same error when running in development mode(but the app works smoothly).

I downgraded the package to the previous version(**2.7.1**) and everything works fine. 

Thank you for your help and great package!

**Comment by husayt** [comment]
released 2.8.3 which hopefully resolves this. Reopen pls if still happens
