### ISSUE TITLE
update for vuex-module-decorators

### ISSUE THREAD

**Issue by SnooHD** [nuxt-community/nuxt-property-decorator#75]
Hello, i am trying to set the global config from [vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators#configuration-1).
I noticed that this package uses 0.16.1, but it was introduced in [v0.17](https://github.com/championswimmer/vuex-module-decorators/blob/master/CHANGELOG.md#0170)

Could you be so kinda to update it to the latest version? :)
Thanks! 👯‍♂️

**Comment by husayt** [comment]
Released 2.8.3 with latest changes

**Comment by kibala145** [comment]
This issue shouldn't be closed(correct me if I'm wrong), it's still not possible to import config from [vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators)

@husayt
