### ISSUE TITLE
Nuxt Hook not registering

### ISSUE THREAD

**Issue by MoronixProduct3** [nuxt-community/nuxt-property-decorator#81]
### Description
In the following sample, the `middleware` Nuxt hook isn't being picked up.
`middleware` is listed amongst the list of supported Nuxt hooks.
```js
import { Component, Vue } from "nuxt-property-decorator"

@Component
export default class CreateUserDialog extends Vue {
  middleware = 'redirect' // This hook is ignored and a `data` field is registered
}
```

### Workaround
Pass the hook directly to the underlying object
```js
import { Component, Vue } from "nuxt-property-decorator"

@Component ({ middleware: 'redirect'})
export default class CreateUserDialog extends Vue {
  ...
}
```

**Comment by husayt** [comment]
@MoronixProduct3  can I ask you to check something for me?

Add this to one your client side plugins (preferably, those called earlier)
```
import "nuxt-property-decorator"
```

Does it get resolved ?
