### ISSUE TITLE
the invoke order of 'head' and 'asyncData' seems not correct

### ISSUE THREAD

**Issue by heyheyhh** [nuxt-community/nuxt-property-decorator#82]
When I debug my nuxt project, it seems that 'head' is invoked before 'asyncData'.

If so, I can't inject my data from 'asyncData' response into html head node.

pls help me resolve this problem.

Thx

**Comment by husayt** [comment]
Seems like this is nuxt specific issue and not something to do with this library. Please, check with them [here](https://github.com/nuxt/nuxt.js). 

If you still think that the issue is here, please, provide an example
