### ISSUE TITLE
Nuxt 3.0 support

### ISSUE THREAD

**Issue by Akihiro1001** [nuxt-community/nuxt-property-decorator#88]
【question】
Could you please tell me if you plan to support this project when Nuxt3 arrives?
I'd like to know if that policy has changed

**Comment by TokugawaTakeshi** [comment]
Looks like there are [some plannings](https://github.com/nuxt-community/nuxt-property-decorator/issues/83) to support it.

Personally I and my methodology very need this support.

## Update

Unfortunately, the author of this package (or one of them) declared that he does not going to develop this package anymore.
https://github.com/nuxt-community/nuxt-property-decorator/issues/83#issuecomment-1085161718
